blank_issues_enabled: false
contact_links:
  - name: 🦆 byPixelTV's Discord
    url: https://dsc.gg/byPixelTV
    about: For general help with RediVelocity join byPixelTV's Discord
  - name: 🚰 SpigotMC Resource
    url: https://www.spigotmc.org/resources/redivelocity.117507/
    about: Read about RediVelocity!